### ISSUE TITLE
What's the recommended browser?

### ISSUE THREAD

**Issue by feklee** [pac-dev/AudioMasher#5]
I tried with Chrome and Firefox on Windows 10. However, with both browsers there are issues. Take for example `440 0.5 sine`:

  * Chrome: patch plays correctly, but there are clicks

  * Firefox: volume starts at 0.5 then quickly approaches 1

**Comment by pac-dev** [comment]
In my testing, it works well in both Chrome and Firefox (also on Windows 10), though FF tends to stutter for a split second when starting audio. For larger patches, it helps to have a beefy processor, however, something as simple as `440 0.5 sine` works correctly even on my $100 smartphone (on Chrome for Android).

Some laptops/processors allow you to select between "energy-saving" or "performance" modes (or similar). On my older laptop, I need to select the latter for AudioMasher to run smoothly. Maybe something to look into.

As for the volume changing, that's never happened to me. Seems more like the kind of thing that happens when annoying Realtek drivers throw in a dynamics compressor at the OS level.

**Comment by feklee** [comment]
Indeed, the volume issue went away after adjusting the audio driver, namely turning off *Dolby Atmos* (shudder):

<img width="307" alt="2018-01-28 01_dolby_atmos" src="https://user-images.githubusercontent.com/14994/51826541-92f79680-22e7-11e9-9ca0-f56985f981c8.png">

Now, there still are the clicks in Chrome, even at maximum performance (8th gen i7, 16 GiB RAM). But things work fine in Firefox!

Anyhow, thank you for making Sporth run in the browser, it's a lot of fun! (Paul pointed me to it.)
