### ISSUE TITLE
play-button missing in web interface

### ISSUE THREAD

**Issue by swestlake** [pac-dev/AudioMasher#6]
the demo of audiomasher online features play-buttons. 
The go-lang instance shows examples, but has no play-test available.
os system- linux

**Comment by pac-dev** [comment]
Open the browser debug console (F12) and see if there are any errors. If the JS or WASM fails to run, the play button won't show up (I should probably make it display a proper error).

A common problem with WebAssembly is that the server sends the WASM file with the wrong content-type. `sporthem.wasm` needs to be served with the HTTP header `content-type: application/wasm` or else browsers refuse to run it. A lot of servers don't do this by default because WASM is relatively new. So the server (whatever you're using to serve the static files) might need to be updated or configured manually to add this header for this file.
